name: VAEditor CI

on: push

jobs:
  buildAndTest:
    runs-on: [windows-latest, ubuntu-latest, macos-latest]

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, build, test
      run: |
        npm install
        npm run build
        npm test
      env:
        CI: true

  checkCodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: Install and check codestyle
      run: |
        npm install
        npm run codestyle
      env:
        CI: true